services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: text-mgmt-system-dev
    command:
      - ./docker-entrypoint.sh
      - python
      - manage.py
      - runserver
      - 0.0.0.0:8000
    # ports:
    #   - "8000:8000"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
      DEBUG: "1"
    volumes:
      - .:/app:delegated
    depends_on:
      db:
        condition: service_started

  proxy:
    build:
      context: ./nginx
    ports:
      - "443:443"       # HTTPS
      - "80:80"         # Redirect to HTTPS
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    external: false

volumes:
  postgres_data:
