# backend/Dockerfile.dev
# Development Dockerfile for the Django backend

# Use a base image with Python
FROM python:3.12 AS backend

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
COPY requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir -r requirements.dev.txt

# Copy the application code (will be volume mounted over in docker-compose.dev.yml)
COPY . .

# Expose the port the Django dev server runs on
EXPOSE 8000

# Command to run the Django dev server (overridden in docker-compose.dev.yml)
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]