# Generated by Django 5.2 on 2025-04-30 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="English name of the language, e.g. 'English', 'German', 'French'",
                        max_length=200,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 639-1 two-letter code, e.g. 'en', 'de', 'fr'",
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="TextChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "alternate_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("first_name", "last_name"),
                        name="unique_first_last_names",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TextChunkMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edition", models.CharField(blank=True, max_length=50, null=True)),
                ("publish_date", models.DateField(blank=True, null=True)),
                (
                    "publication_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("unknown", "Unknown"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier, such as an ISBN, DOI, custom ID, etc.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(blank=True, to="text_management.author"),
                ),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="text_management.language",
                    ),
                ),
                (
                    "publishers",
                    models.ManyToManyField(blank=True, to="text_management.publisher"),
                ),
                (
                    "text_chunk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="text_management.textchunk",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="text_management.title",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text chunks metadata",
                "verbose_name_plural": "Text chunks metadata",
            },
        ),
    ]
