# Generated by Django 5.2 on 2025-04-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="English name of the language, e.g. 'English', 'German', 'French'",
                        max_length=200,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 639-1 two-letter code, e.g. 'en', 'de', 'fr'",
                        max_length=2,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
