# Generated by Django 5.2 on 2025-04-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textchunkmetadata",
            name="text_chunk",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metadata",
                to="text_management.textchunk",
            ),
        ),
    ]
