# Generated by Django 5.2 on 2025-04-29 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("text_management", "0002_publisher_textchunk_title_author_textchunkmetadata"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="textchunkmetadata",
            options={
                "verbose_name": "Text chunks metadata",
                "verbose_name_plural": "Text chunks metadata",
            },
        ),
        migrations.AddField(
            model_name="textchunkmetadata",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="text_management.language",
            ),
        ),
    ]
